### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by casperdcl** [conjuring/conjuring#1]
# TODO

- [x] one or some combination of
  + [ ] multi-container, single-server per container
    * high RAM requirement
    * full isolation
  + [ ] multi-server, multi-container
    * intended use case is to run on multiple host machines (e.g. [z2jh](https://z2jh.jupyter.org))
    * probably excessive
  + [x] multi-server, single-container
    * probably best compromise (essentially dockerised version of [tljh](https://tljh.jupyter.org))
- [ ] fork/base off `darribas/gds_env`
- [x] conda (or virtualenv or root)
  * probably best to use miniconda (reasonably lightweight, provides both conda and pip)
- [x] requirements.txt/[environment.yml](https://github.com/binder-examples/python-conda_pip/blob/master/environment.yml)
  * how to specify core and custom installation packages
- [ ] notebook repositories
  + to be cloned/copied per user into home directories?
  + [ ] `kingsgeocomp/code-camp`
  + [ ] `kingsgeocomp/geocomputation`
  + [ ] `kingsgeocomp/spatial-analysis`
  + [ ] `jreades/urb-studies-predicting-gentrification`
  + `darribas/gds18`?
  + `darribas/gds_ufmg19`?
- [ ] sudo user permissions?
- [x] generation and management of
  + [ ] port
  + [x] username
  + [x] password
  + [x] workspace/dir
- [ ] SSL & security

# Links
- [blog](https://kingsgeocomputation.org/2019/04/25/conjuring/)
- [kingsgeocomp@GH](https://github.com/kingsgeocomp/)
- [kingsgeocomp/code-camp](https://github.com/kingsgeocomp/code-camp)
  + entry-level repo that we ask our students to tackle over the summer before they start Geocomputation
- [kingsgeocomp/geocomputation](https://github.com/kingsgeocomp/geocomputation)
  + Year 2, Term 1 intro module and has a setup.yml file for configuring a conda environment
- [kingsgeocomp/spatial-analysis](https://github.com/kingsgeocomp/spatial-analysis)
  + Year 2, Term 2 module
- [jreades/urb-studies-predicting-gentrification](https://github.com/jreades/urb-studies-predicting-gentrification)
  + about the limit of what I’d expect to demo on the system, so it might be a good test
- [darribas/gds_env](https://github.com/darribas/gds_env)
  + attempt at compiling everything we usually need for geographic data science and put it into a container. In my mind, this is what would form the basis of the hub (since it pulls from the official Jupyter stack, the hub is enabled already, so it needs very little overhead to get it up and running. And the less reinventing we do, I think the better.
- [darribas/gds18](https://github.com/darribas/gds18)
  + At Liverpool I teach this course that encapsulates a lot of what I usually do in workshops and other teaching engagements. After four years, we’ve got the install relatively smooth on campus, but it’s still a native install on Windows which is not great. I’d love to teach it relying on say the gds_env, but apparently it’s very hard to deploy Docker on campus managed machine
  + you can see a bit more of the background for the course on this recent paper [10.21105/jose.00042](https://jose.theoj.org/papers/10.21105/jose.00042)
- [darribas/gds_ufmg19](https://github.com/darribas/gds_ufmg19)
  + one of my most recent workshops. I ran that out of binder (link in there) and out of Azure Notebooks (project link). Since it’s not clear how much longer Microsoft will keep it free, that’s an additional motivation Conjuring
- [jupyter/nbgrader](https://github.com/jupyter/nbgrader)
  + setting and marking assignments
- [jupyter/repo2docker](https://github.com/jupyter/repo2docker)
  + create a jupyter-enabled docker image from a repository (probably too general)
- https://github.com/NVIDIA/nvidia-docker/issues/568
  + `nvidia` driver with `docker-compose`
- [ipython-contrib/jupyter_contrib_nbextensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions)
  + useful Jupyter customisation options
- [jupyter-widgets/ipywidgets](https://github.com/jupyter-widgets/ipywidgets)
  + widgets provider
- [jupyter-widgets/ipyleaflet](https://github.com/jupyter-widgets/ipyleaflet)
  + interactive maps in widgets
- [jupyterhub/nbgitpuller](https://github.com/jupyterhub/nbgitpuller)
  + one-way sync (remote->local) git repos, auto-resolving conflicts
- [kidig/rpi-jupyter-lab](https://github.com/kidig/rpi-jupyter-lab)
  + "slow at best" but nice proof-of-concept
- [rsbivand/ectqg19-workshop](https://github.com/rsbivand/ectqg19-workshop)
  + workshop materials for early Sept 2019
